### ISSUE TITLE
Avatar image broken

### ISSUE THREAD

**Issue by John2dot0** [codemortals/game-platform#19]
Top right avatar image is showing broken image icon.

![avatar](https://user-images.githubusercontent.com/28757371/82707465-16aa6480-9c4a-11ea-926e-76b2ae4848e5.JPG)

**Comment by John2dot0** [comment]
Additional screenshot.
![image](https://user-images.githubusercontent.com/28757371/82707635-76087480-9c4a-11ea-866f-8a7417503425.png)

**Comment by John2dot0** [comment]
Issue on my end, due to using incognito mode in browser.

**Comment by eddiejaoude** [comment]
No worries. Thank you for raising and figuring it out. Strange why in `incognito` mode it didnt work. Something we can look into 🤓
