### ISSUE TITLE
A suggestion for a rank list...

### ISSUE THREAD

**Issue by tomlane** [codemortals/game-platform#58]
The ranks from Worms Armegeddon are quite amusing... perhaps they could be used?

https://worms2d.info/Deathmatch

**Comment by eddiejaoude** [comment]
LOL 😂 

<img width="1081" alt="Screenshot 2020-06-27 09 25 35" src="https://user-images.githubusercontent.com/624760/85918167-2ffd8c80-b858-11ea-84e2-4d5edca2260f.png">
