### ISSUE TITLE
Users can access choices collection 

### ISSUE THREAD

**Issue by alrifay** [codemortals/game-platform#69]
I have never used fire store before but i'm assuming the issue is in `firestore.rules` line **42**
https://github.com/codemortals/game-platform/blob/7da63689750ff3b6bb3b732f738683e52e941ee7/firestore.rules#L41-L44

---

I was looking in the repository trying to understand how the game works and find out if i can get the answers and i found there is a collection called `choices`
https://github.com/codemortals/game-platform/blob/7da63689750ff3b6bb3b732f738683e52e941ee7/functions/src/quiz/round-end.ts#L66-L70

Then i opened chrome devtools -> sources tab and search for `findOne`
https://github.com/codemortals/game-platform/blob/3ed9c0b128614573211a42e370751d2e302d8a97/hosting/src/app/games/quiz/answer.service.ts#L45

I found the function in a minified file called `9-es2015.df87b63f5b6ddb20d914.js`
Then i enabled [Local Overrides](https://developers.google.com/web/updates/2018/01/devtools#overrides) and formatted the file  and logged choices and made `angularFirestore` a global variable
```javascript
class e {
    constructor(e, n) {
        window.angularFirestore = e;
        (this.angularFirestore = e), (this.authenticationService = n);
    }
    create(e, n, t, i) {
        const s = { user: this.authenticationService.user.getValue().uid, response: i, created: A.firestore.FieldValue.serverTimestamp() },
            c = this.angularFirestore.collection('quizzes').doc(e).collection('rounds').doc(n).collection('questions').doc(t).collection('answers').doc(s.user);
        return Object(b.a)(c.set(s));
    }
    findOne(e, n, t) {
        const i = this.authenticationService.user.getValue().uid;
        const questionRef = this.angularFirestore.collection('quizzes').doc(e).collection('rounds').doc(n).collection('questions').doc(t);
        questionRef
            .collection('choices')
            .valueChanges()
            .subscribe((choices) => console.log('choices:', choices.filter(({ correct }) => correct)));
        return questionRef.collection('answers').doc(i).valueChanges();
    }
}
```
And the result is I was able to log all choices, change my alias, avatar and rank 😁
```javascript
angularFirestore.collection('users').doc("QhXZk62eW8buiC0XlpqhB78PTYD3").set({
    avatar: 'https://raw.githubusercontent.com/alrifay/alrifay/master/resources/mohammad.svg',
    alias: 'Mohammad',
    level: {
        display: '😏😏😏😏😏',
        experience: 10
    }
}, { merge: true })
```
![image](https://user-images.githubusercontent.com/19517534/89080677-d07c2a80-d389-11ea-87fd-96b9bac88211.png)
![image](https://user-images.githubusercontent.com/19517534/89080903-7334a900-d38a-11ea-8b07-2f9ffccdcad0.png)

**Comment by eddiejaoude** [comment]
@alrifay WOW 😱 (great issue 💪 )  - I thought your `level` had changed and I forgot to ask on the stream 🤓
