### ISSUE TITLE
Markdown XSS Vulnerability 🙄

### ISSUE THREAD

**Issue by alrifay** [codemortals/game-platform#70]
I found out that questions support markdown.
https://github.com/codemortals/game-platform/blob/67a647f08bffa5aa95e0ae47e3c25194c6c6d6fd/hosting/src/app/games/quiz/question/question.component.html#L12

So i tried creating a new question contains the following code.

```html
<a href="javascript:alert('Hello'),document.querySelectorAll('.brand-card').forEach(el=>el.style.backgroundColor='royalblue')">Click me</a>
```
And the result is:
![Result](https://user-images.githubusercontent.com/19517534/89111355-29fd5b80-d455-11ea-8154-618abfc645ae.gif)

Sample game: https://gaming.codemortals.com/games/knIiFip0OUPF5z8O2COp/play

Why does questions support markdown? i don't think it's necessary 😁

**Comment by eddiejaoude** [comment]
@alrifay great spot on those problems and issue write up 🎉 These are so important, thank you 💪
